### ISSUE TITLE
Using pqc-kyber NPM

### ISSUE THREAD

**Issue by AltFreq07** [Argyle-Software/kyber#1]
I would really like to try and use the NPM package with the WASM implementation but am having issues
This relative module was not found:       

 ```
This relative module was not found:
* ./pqc_kyber_bg.js in ./node_modules/pqc-kyber/pqc_kyber_bg.wasm  

```

Is there an example implementation around anywhere with the wasm exports being used?

I've also tried building it myself from this repo but am met with the "js" feature issue below. Unfortunately this was my first interaction with rust and I am unable to solve.

```
wasm-pack build -- --features wasm
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling wasm-bindgen-shared v0.2.74
   Compiling log v0.4.14
   Compiling cfg-if v1.0.0
   Compiling bumpalo v3.7.0
   Compiling lazy_static v1.4.0
   Compiling cc v1.0.68
   Compiling wasm-bindgen v0.2.74
   Compiling getrandom v0.2.3
error: the wasm32-unknown-unknown target is not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> /home/altfreq/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/lib.rs:219:9
    |
219 | /         compile_error!("the wasm32-unknown-unknown target is not supported by \
220 | |                         default, you may need to enable the \"js\" feature. \
221 | |                         For more information see: \
222 | |                         https://docs.rs/getrandom/#webassembly-support");
    | |_________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /home/altfreq/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/lib.rs:246:5
    |
246 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown" "--features" "wasm"
```

**Comment by zkbitcoin** [comment]
add this in Cargo 

getrandom = { version = "0.2.7", features = ["js"] }

**Comment by mberry** [comment]
There was some API changes from  `0.1` so you will also have to modify the wasm module to accommodate that.

When I get some time this week I'll patch it up and publish to npm. Will bump the crates version with a zeroise feature also.

**Comment by zkbitcoin** [comment]
> There was some API changes from `0.1` so you will also have to modify the wasm module to accommodate that.
> 
> When I get some time this week I'll patch it up and publish to npm. Will bump the crates version with a zeroise feature also.

btw, awesome library works like a charm, running it here , great work (WASM binary on the client executing without a hitch)

https://zkbitcoin.com/qm?algorithm=Kyber

**Comment by mberry** [comment]
New version published: https://www.npmjs.com/package/pqc-kyber

Also added:

* Readme with js examples in [pkg/](https://github.com/Argyle-Software/kyber/tree/master/pkg)
* Runnable demo in [www/](https://github.com/Argyle-Software/kyber/tree/master/www)
