### ISSUE TITLE
Fails to compile on MacOS

### ISSUE THREAD

**Issue by thomwiggers** [Argyle-Software/kyber#2]
The assembly files included for the AVX2 code don't export underscore-prefixed names, which is what the ABI on MacOS expects. Thus this crate fails to compile on Mac. (without specifying `reference`)

**Comment by faern** [comment]
Just for the record, and anyone else landing on this issue. This library builds and runs out of the box on Apple Silicon based Macs. And it also works on Intel based macs if you enable the feature `reference`.

**Comment by mberry** [comment]
After multiple attempts have been unable to get MacOS running in virtualbox/vmware and don't own any apple hardware. Was using (abusing?) github actions for some debugging a while ago but was fruitless.
At this point will probably have to find a vps provider with mac compute.

Mac x86_64 is still using the System V ABI as linux/bsd does so will have to look into why there is some differences with the calling conventions here. The underscore prefix names are all constants and not called by the library. 

All the external function calls are listed here: 

https://github.com/Argyle-Software/kyber/blob/6e274dcd11ef85b7aa642be24054a3847683d293/src/avx2/poly.rs#L44-L58

**Comment by mberry** [comment]
So I have this passing all tests on `x86_64-apple-darwin` however the macos-latest ci runner seems to be failing with vague build script (cc) error messages, not sure if there is anything else required to use cc on the runner, it doesn't seem like it, will have to investigate. Until that gets fixed will hold off merging. The branch is usable for now.

https://github.com/Argyle-Software/kyber/tree/macOS-fix

[1] https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md
