### ISSUE TITLE
Add git tags for releases

### ISSUE THREAD

**Issue by faern** [Argyle-Software/kyber#24]
A common and very good practice is to add git tags to the commits where a crate was published from. This makes it so much easier to find the relevant code and see code diffs between releases. I would appreciate this a lot.

**Comment by mberry** [comment]
Am not particularly a fan of github releases and usually prefer crates.io or local paths for package management personally but am open to doing it.

Tags are certainly fine. If anyone wants to spin up an actions CI script that does a github release on version tags I'm ok with that and it would streamline the whole process.

Looking to increase the version cadence in the next few months and move towards a properly stabilised 1.0 sometime next year. This includes traits, finalising feature branches and neon optimised support at a minimum.

**Comment by faern** [comment]
I'm not requesting github releases at all! Just git tags. So when I want to look into the source code for a certain release I can easily find it. And easier see code diffs between releases.

**Comment by mberry** [comment]
Releases are now in CI on tagged commits pushed to master
