### ISSUE TITLE
Implement PKE

### ISSUE THREAD

**Issue by tbraun96** [Argyle-Software/kyber#30]
Performing key-exchange with Kyber is only half the story. Using the resulting keys to perform encryption/decryption of chosen plaintexts should also be a feature of this crate.

**Comment by tbraun96** [comment]
When you say "kyber alone", what do you mean? This [document clearly implies](https://pq-crystals.org/kyber/data/kyber-specification-round2.pdf) that PKE is part of the Kyber ecosystem.

**Comment by 13-05** [comment]
Hey, @tbraun96! It looks like you were able to [implement this functionality independently](https://docs.rs/kyber-pke/latest/kyber_pke/)? I stumbled upon it when looking for a way to handle CRYSTALS-Kyber encryption in Rust, and it seems your library is the most complete (it was honestly the only one I could find). I'm not the best at cryptography (hence why I'm not implementing the encryption myself...), so I was wondering if you feel your implementation is cryptographically sound. I *will* follow the recommendation to use Kyber in a "hybrid mode" of course, but I'm wondering if your implementation is fine or if I should just wait for a more established implementation to be developed.

**Comment by bwesterb** [comment]
> so I was wondering if you feel your implementation is cryptographically sound.

It's not: it uses the inner "indcpa" PKE which has malleable ciphertexts. Don't use it. Instead, [use HPKE with full IND-CCA2 Kyber](https://github.com/bwesterb/rust-hpke).

**Comment by 13-05** [comment]
> > so I was wondering if you feel your implementation is cryptographically sound.
> 
> It's not: it uses the inner "indcpa" PKE which has malleable ciphertexts. Don't use it. Instead, [use HPKE with full IND-CCA2 Kyber](https://github.com/bwesterb/rust-hpke).

Thanks!

**Comment by tarcieri** [comment]
Hello, I'm writing on behalf of the @RustCrypto project.

We maintain the `kem` crate which provides an abstraction over KEMs: https://github.com/RustCrypto/traits/tree/master/kem

It would be interesting for this crate to implement those traits. See `pqcrypto-compat` as an example: https://github.com/rozbb/pqcrypto-compat

There's also this existing implementation of HPKE it should be possible to plug Kyber into: https://github.com/rozbb/rust-hpke

cc @rozbb

**Comment by bwesterb** [comment]
rust-hpke has support for Kyber (in a branch), see https://github.com/rozbb/rust-hpke/pull/43

**Comment by mberry** [comment]
Hey Tony, certainly keen to add those KEM traits (#10) but was trying to avoid a `GenericArray` dependency, not particularly sure on the timeline for expanded const generics, there's a few of QoL improvements in this crate it would enable. 

Would be happy with the traits behind a feature gate though.

**Comment by tarcieri** [comment]
@mberry our next release will get rid of `generic-array`, however unfortunately we can't fully migrate to const generics yet and are instead migrating to [`hybrid-array`](https://github.com/RustCrypto/utils/tree/master/hybrid-array) which at least has better const generic interop. Unfortunately we make use of [associated size constants](https://docs.rs/kem/latest/kem/trait.EncappedKey.html#associatedtype.SharedSecretSize) which [don't yet interoperate with const generics](https://github.com/rust-lang/rust/issues/60551).

Feature gating the functionality seems like a good way to avoid the extraneous dependencies.

**Comment by mberry** [comment]
HPKE is big scope and OOB for this project.

You can find a proposal on how to do this here: https://datatracker.ietf.org/doc/draft-westerbaan-cfrg-hpke-xyber768d00/

Closed for housekeeping reasons. Always happy to discuss it further though.
