### ISSUE TITLE
Expose CPA primitives

### ISSUE THREAD

**Issue by tbrezot** [Argyle-Software/kyber#31]
Hello,

We are working on the hybridization of [our scheme](https://github.com/Cosmian/cover_crypt/pull/30). We are using your library because it allows compiling to WASM. However, we would like to be able to use the CPA-Kyber primitives.

Could you consider making the `reference` module public?

Regards,

**Comment by mberry** [comment]
Hi, I've look through your repo and can't tell what primitives you are needing, which module/s in particular? 

Regardless, I'm fine with this, but would put it behind a hazmat feature gate with some usage warning to expose internals.

**Comment by tbrezot** [comment]
Hey, thank your answer.

I would need the primitives of IND-CPA Kyber that are in [`reference::indcpa`](https://github.com/Argyle-Software/kyber/blob/master/src/reference/indcpa.rs). Namely, `indcpa_keypair`, `indcpa_enc` and `indcpa_dec`.

Sure I agree this should not be exposed by default.

I [forked your repo](https://github.com/tbrezot/kyber/tree/feat/expose_indcpa_primitives) waiting for this change to be made upstream. I would propose a MR but it seems your editor leaves trailing spaces at the end of lines (while mine removes them on save) and that you are not using `rustfmt` so it is a bit tedious to get clean diffs...

Would you consider sticking to the `rustfmt` format or indicating how to format your code the way you do (I couldn't find it in your readme)?

Apart from exposing these primitives, I think I have spotted deprecated documentations which refer to [`KYBER_INDCPA_MSGBYTES`](https://github.com/Argyle-Software/kyber/blob/master/src/reference/indcpa.rs#L243) when no constant is declared with this name in the crate. As I understood, it should be replaced by [`KYBER_SYMBYTES`](https://github.com/Argyle-Software/kyber/blob/f8db3fb0f44952a1431d91c07acf330187993745/src/reference/poly.rs#L308).

**Comment by tbrezot** [comment]
I have exposed the primitives in #36

**Comment by tbrezot** [comment]
Merged in #36
