### ISSUE TITLE
compile time error for no_std

### ISSUE THREAD

**Issue by oilel** [Argyle-Software/kyber#49]
use pqc_kyber::*;
fn main(){
    let mut rng = rand::thread_rng();
    let pair = keypair(&mut rng);
    let (ct, ss) = encapsulate(&pair.public, &mut rng)?;
}
#[panic_handler]
fn my_panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

#[lang = "eh_personality"]
extern "C" fn eh_personality() {}

Still get compile time error:
error: `#[panic_handler]` function required, but not found

error: language item required, but not found: `eh_personality`
  |
  = note: this can occur when a binary crate with `#![no_std]` is compiled for a target where `eh_personality` is defined in the standard library
  = help: you may be able to compile for a target that doesn't need `eh_personality`, specify a target with `--target` or in `.cargo/config`

**Comment by oilel** [comment]
These errors may be caused when compiling zeroize, since I specified zeroize feature for this crate.

**Comment by oilel** [comment]
I use Termux, a terminal emulator for Android, on ARM64.

**Comment by mberry** [comment]
Is this with the [`std` feature enabled ](https://github.com/Argyle-Software/kyber/blob/d20228b6029d7d113f5d6218763f9558c44f847e/Cargo.toml#L73)for Kyber?

**Comment by oilel** [comment]
> Is this with the [`std` feature enabled ](https://github.com/Argyle-Software/kyber/blob/d20228b6029d7d113f5d6218763f9558c44f847e/Cargo.toml#L73)for Kyber?

No.

**Comment by mberry** [comment]
Enable `std` and you should be fine. Please update if there's any more problems. 

I should make a note somewhere in the readme about no_std and exception handling.

**Comment by mberry** [comment]
Is this still causing any problems?

**Comment by oilel** [comment]
> Is this still causing any problems?

No.
