### ISSUE TITLE
"90s" feature breaks no_std builds due to "std" feature being added on sha2

### ISSUE THREAD

**Issue by k3d3** [Argyle-Software/kyber#58]
![image](https://user-images.githubusercontent.com/1247908/214972026-74f940c4-6b2a-438d-a310-7f72f6de24bc.png)

I think this is fixable by adding `default-features = false` to the `sha2` dependency.

**Comment by mberry** [comment]
Thanks for the report, I call roll this up into a patch version soon, `digest/std` and `block-buffer` doesn't need to be pulled in.
